---
driver:
  name: vagrant
  customize:
    memory: 1024

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[mysql_test::server]
      - recipe[mysql_management::default]
      - recipe[mysql_management::backups]
    attributes:
      dev_mode: true
